export const KNOWN_RATE_LIMIT_WAF_SIGNATURES = [
  // Akamai
  //{ regex: /Access Denied/i, statuses: [403] },
  { regex: /Reference #/i, statuses: [403] },
  // {
  //   regex: /You don't have permission to access .* on this server\./i,
  //   statuses: [403],
  // },

  // AWS WAF / CloudFront
  { regex: /Blocked by AWSWAF/i, statuses: [403, 429] },
  { regex: /Generated by cloudfront \(CloudFront\)/i, statuses: [403, 429] },
  { regex: /Request blocked\./i, statuses: [403, 429] },
  { regex: /The request could not be satisfied\./i, statuses: [403, 429] },
  { regex: /id=["']aws-waf-captcha-container["']/i, statuses: [403, 405] },
  { regex: /id=["']aws-waf-interstitial["']/i, statuses: [403, 405] },

  // Azure Web Application Firewall
  { regex: /The request is blocked\./i, statuses: [403, 405, 406, 429] },

  // Barracuda
  { regex: /Barracuda Web Application Firewall/i, statuses: [403] },
  {
    regex:
      /The requested URL was rejected\. Please contact the administrator\./i,
    statuses: [403],
  },

  // BitNinja
  { regex: /Security check by BitNinja/i, statuses: [403, 503] },
  { regex: /Visitor anti-robot validation/i, statuses: [403, 503] },
  { regex: /your IP will be removed from BitNinja/i, statuses: [403] },

  // Citrix NetScaler
  { regex: /Citrix Web App Firewall/i, statuses: [403, 200] },
  { regex: /Request denied by Citrix Web App Firewall/i, statuses: [403] },

  // Cloudflare
  { regex: /Attention Required! \| Cloudflare/i, statuses: [403] },
  { regex: /Checking if the site connection is secure/i, statuses: [403, 503] },
  { regex: /Cloudflare Ray ID:/i, statuses: [403, 429, 503] },
  { regex: /Ray ID:/i, statuses: [403, 429, 503] },
  { regex: /Direct IP access not allowed/i, statuses: [403] },
  { regex: /Error 1020: Access Denied/i, statuses: [403] },
  { regex: /Performance & security by Cloudflare/i, statuses: [403, 503] },
  { regex: /Please wait while we verify\.\.\./i, statuses: [403, 503] },
  { regex: /Performing security verification/i, statuses: [403] },
  {
    regex:
      /This website is using a security service to protect itself from online attacks\./i,
    statuses: [403, 503],
  },
  { regex: /id=["']cf-wrapper["']/i, statuses: [403, 429, 503] },
  { regex: /id=["']cf-error-details["']/i, statuses: [403, 503] },
  { regex: /id=["']challenge-form["']/i, statuses: [403, 503] },
  { regex: /id=["']turnstile-wrapper["']/i, statuses: [403, 503] },
  { regex: /class=["'][^"']*cf-error-code[^"']*["']/i, statuses: [403, 503] },

  // DataDome
  { regex: /id=["']datadome-captcha-container["']/i, statuses: [403, 429] },
  {
    regex: /class=["'][^"']*datadome-captcha[^"']*["']/i,
    statuses: [403, 429],
  },
  { regex: /src=["'][^"']*datadome\.co\/tags\.js["']/i, statuses: [403, 429] },

  // F5 BIG-IP & Shape Security
  { regex: /Support ID:/i, statuses: [403, 406] },
  { regex: /Your support ID is:/i, statuses: [403, 406] },
  {
    regex:
      /The requested URL was rejected\. Please consult with your administrator\./i,
    statuses: [403, 406],
  },
  { regex: /id=["']shape-captcha["']/i, statuses: [403] },
  {
    regex: /src=["'][^"']*\/_imp_apg_pt_[^"']*["']/i,
    statuses: [200, 403, 406],
  },

  // Fastly (Signal Sciences)
  { regex: /Error 406 - Not Acceptable/i, statuses: [406] },

  // Fortinet FortiWeb
  { regex: /FortiWeb Web Application Firewall/i, statuses: [403] },

  // Imperva / Incapsula
  { regex: /Error 15/i, statuses: [403] },
  { regex: /Error 16/i, statuses: [403] },
  { regex: /Error 20/i, statuses: [403] },
  { regex: /Incident ID:/i, statuses: [403, 429] },
  { regex: /Powered by Imperva/i, statuses: [403, 429] },
  { regex: /Powered by Incapsula/i, statuses: [403, 429] },
  {
    regex: /src=["'][^"']*\/_Incapsula_Resource\?[^"']*["']/i,
    statuses: [403, 429, 200],
  },

  // ModSecurity
  { regex: /ModSecurity Action/i, statuses: [403, 406] },
  { regex: /This error was generated by ModSecurity/i, statuses: [403, 406] },
  { regex: /Web Application Firewall ModSecurity/i, statuses: [403, 406] },

  // PerimeterX / HUMAN Security
  { regex: /id=["']px-captcha["']/i, statuses: [403] },
  { regex: /window\._pxAppId\s*=/i, statuses: [403] },

  // Radware
  { regex: /Access denied by Radware/i, statuses: [403] },
  { regex: /Unauthorized Access .* Radware/i, statuses: [403] },
  { regex: /Cloud WAF CAPTCHA/i, statuses: [503, 403] },

  // SiteLock
  { regex: /SiteLock Incident ID/i, statuses: [403, 429] },
  { regex: /SiteLock TrueShield/i, statuses: [403, 429] },
  {
    regex: /Sitelock is protecting this website from malicious activity/i,
    statuses: [403, 429],
  },

  // StackPath / MaxCDN
  {
    regex:
      /You performed an action that triggered the service and blocked your request\./i,
    statuses: [403],
  },
  { regex: /StackPath WAF/i, statuses: [403] },

  // Sucuri
  { regex: /Access Denied - Sucuri Website Firewall/i, statuses: [403] },
  { regex: /Block details:/i, statuses: [403] },
  { regex: /Block ID:/i, statuses: [403] },
  {
    regex: /Block reason: Your request was not authorized due to its content/i,
    statuses: [403],
  },
  { regex: /CloudProxy is a WebSite Firewall from Sucuri/i, statuses: [403] },
  { regex: /Sucuri CloudProxy/i, statuses: [403] },
  { regex: /class=["'][^"']*sucuri-block[^"']*["']/i, statuses: [403] },
  { regex: /class=["'][^"']*sucuri-block-details[^"']*["']/i, statuses: [403] },

  // Wordfence
  {
    regex:
      /A potentially unsafe operation has been detected in your request to this site\./i,
    statuses: [403],
  },
  { regex: /Block Technical Data/i, statuses: [403] },
  { regex: /Generated by Wordfence/i, statuses: [403, 503] },
  {
    regex: /Your access to this service has been limited\./i,
    statuses: [403, 503],
  },
  {
    regex: /Your access to this site has been limited by the site owner\./i,
    statuses: [403, 503],
  },

  // Other
  {
    regex: /Sorry, we need to verify that this request is legitimate/,
    statuses: [403],
  },
  {
    regex: /Your connection needs to be verified before you can proceed/,
    statuses: [403],
  },
  { regex: /\(robot\)/, statuses: [403] },
];
